import { Rule, SchematicContext, Tree } from '@angular-devkit/schematics';
import { execSync } from 'child_process';
export function generateHeaderComponent(options: any): Rule {
  return (tree: Tree, _context: SchematicContext) => {
    execSync(`ng g c header --skip-tests`, { stdio: [0, 1, 2] });
    const htmlCode = `<header>
    <a>AutoGenerated</a>
    </header>`;
    tree.overwrite(`${options.path}/header/header.component.html`, htmlCode);

    const cssCode = `header {
    background: transparent linear-gradient(90deg, #3E5977 10%, #263E6C 100%);
    color: #FFFFFF;
    text-align: left;
    padding: 15px;
    display: flex; 
    align-items: center;
    }


    @media (max-width: 768px) {
        header {
            flex-direction: column;
            align-items: center;
        }
        
    }
      `;
    tree.overwrite(`${options.path}/header/header.component.css`, cssCode);

    return tree;
  };
}
